### PR TITLE
Add a library comparison table to the README

### PR DESCRIPTION
**Pull request by NebelNidas**

### CODE REVIEW

**Review by modmuss50 — CHANGES_REQUESTED** [review]
No.

Im not a fan of these comparison tables, I dont think this is needed. Maybe just say what mapping-io can do without trying to throw shade towards the other libraries.

**Comment by NebelNidas** [comment]
This was in no way intended to de-legitimize other people's work, rather as a quick and easy way to help consumers make informed decisions on which library to use, based on the feature sets they desire. This table addresses MIO's shortcomings just as much as as the alternatives'.

**Comment by SpaceWalkerRS** [comment]
should something like this not be somewhere independent of the libraries it's comparing, to avoid the impression of bias?

**Comment by NebelNidas** [comment]
I guess I could put it on the wiki, but all that would do is make it less discoverable. I don't see an issue with this frankly, I tried to be as neutral as possible. Mapping-IO checking more boxes than the alternatives is simply a consequence of having the largest feature set 🤷‍♂️

**Pull request closed without merging**
